### PR TITLE
new aesthetic, blue bg -> white

### PR DESCRIPTION
**Pull request by fedderw**
image

### CODE REVIEW

**Comment by fedderw** [comment]
@MaxGhenis @leomatkovsky 
I think this looks better, lmk if you guys do

**Comment by MaxGhenis** [comment]
Agreed, thanks! @ngpsu22

**Comment by MaxGhenis** [comment]
Please delete the commented lines and then feel free to merge and ping Hank to update.

**Comment by fedderw** [comment]
> Please delete the commented lines and then feel free to merge and ping Hank to update.

Could you give me write access to the repo? Thx

**Pull request merged**
